// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXtWBBTbevZhX8V9oVxthNTZrzdsI9Zyc',
    appId: '1:745966745076:web:acd17b2542b9c5d7c235a1',
    messagingSenderId: '745966745076',
    projectId: 'pic-book-irfan',
    authDomain: 'pic-book-irfan.firebaseapp.com',
    storageBucket: 'pic-book-irfan.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFDyn1rtEfFXlbHrIXb5E0IyX3GrXyTQg',
    appId: '1:745966745076:android:c73bf9aa79008c00c235a1',
    messagingSenderId: '745966745076',
    projectId: 'pic-book-irfan',
    storageBucket: 'pic-book-irfan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMTM93GKCvpNdIbyriGdIJUkmGD1-XOwI',
    appId: '1:745966745076:ios:bc4f678e8087bfdec235a1',
    messagingSenderId: '745966745076',
    projectId: 'pic-book-irfan',
    storageBucket: 'pic-book-irfan.appspot.com',
    iosClientId: '745966745076-4ob1oj447o7rtl8tvc1d2js7scn2uq8t.apps.googleusercontent.com',
    iosBundleId: 'picbook.picbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMTM93GKCvpNdIbyriGdIJUkmGD1-XOwI',
    appId: '1:745966745076:ios:bc4f678e8087bfdec235a1',
    messagingSenderId: '745966745076',
    projectId: 'pic-book-irfan',
    storageBucket: 'pic-book-irfan.appspot.com',
    iosClientId: '745966745076-4ob1oj447o7rtl8tvc1d2js7scn2uq8t.apps.googleusercontent.com',
    iosBundleId: 'picbook.picbook',
  );
}
